### ISSUE TITLE
Content-Type

### ISSUE THREAD

**Issue by aRWeeX** [teeli/urltitle#11]
[This](https://github.com/teeli/urltitle/blob/master/urltitle.tcl#L144) doesn't seem correct because sites without `Content-Type` gets through. A `DOCTYPE` check would also be good.

**Comment by FevLoad** [comment]
avieks 
can you fix this script, if you can then just post the edited version here.

**Comment by teeli** [comment]
Do you have an example of a URL without content-type that I could test?

**Comment by aRWeeX** [comment]
If I recall correctly there was no error, just from my side.
