### ISSUE TITLE
Tcl error [UrlTitle::handler]: can't read "delay": no such variable

### ISSUE THREAD

**Issue by dereckhall** [teeli/urltitle#13]
hello, I'm using eggdrop 1.8.1 compiled on a 64bit linux system.

I receive 'Tcl error [UrlTitle::handler]: can't read "delay": no such variable' in the console after loading the script, performing .chanset, and typing a URL in the channel.

on line 98 i see 'variable delay'
I changed this to 'global delay'

this resolved my issue.

**Comment by teeli** [comment]
That's strange. I've never seen that error myself and the delay variable should work like other variables there. What's your TCL version?

**Comment by dereckhall** [comment]
Yeah... it was a bit strange

CentOS 6.9 64bit
  tcl-devel-8.5.7-6.el6.x86_64
  tcl-8.5.7-6.el6.x86_64

**Comment by teeli** [comment]
Actually yeah, it's probably a variable scope issue. I think pull request #12 should fix that, when I get the chance to review, test and merge it properly.

**Comment by teeli** [comment]
This should probably be fixed in master now
