### ISSUE TITLE
Outputs empty $urtitle variable to the IRC channel

### ISSUE THREAD

**Issue by dereckhall** [teeli/urltitle#14]
Hello,

If the script attempts to parse an imgur url (or similar photo etc url) where it is unable to scrape a title, it will output the empty variable to the channel:

<bot> Title:

I added the following to check for an empty $urtitle
          if {$urtitle eq ""} {      
           break
          }

this is directly above:
          if {[string length $urtitle]} {
            puthelp "PRIVMSG $chan :title: $urtitle"
          }
          break
        }
------

**Comment by teeli** [comment]
Yeah, that makes sense. Could you maybe make a pull request?

**Comment by dereckhall** [comment]
done - pull sent.

**Comment by teeli** [comment]
Pull request now merged to master
