### ISSUE TITLE
HTTPS doesn't work

### ISSUE THREAD

**Issue by dchmelik** [teeli/urltitle#18]
In my bots, HTTPS doesn't work with urltitle.0.10.tcl .  If you need to load other scripts to get HTTPS to work, can you please write that documentation?

**Comment by teeli** [comment]
I need some more info about this. What version of TCL are you running? TclTLS? Specific URLS that aren't working?

**Comment by dchmelik** [comment]
The server I use has TCL 8.5, 8.6, and TclTLS 1.7.14.  I don't know which were needed to compile eggdrop 1.8.3.  NO HTTPS URL works... for example, https://google.com .

**Comment by teeli** [comment]
This seems like a configuration issue, but without knowing any specifics I can't say what could be the reason.

**Comment by dchmelik** [comment]
which specifics?
