### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by KeiroD** [teeli/urltitle#2]
Your script doesn't seem to do SSL support. Well, it does say SSL is optional but I'm having trouble trying to get it to actually support HTTPS links.

I have `tcl-tls` installed on the server, so that's not an issue... I also tried adding `package require tls` to urltitle.tcl but that's a no joy. I do see that your script checks for `package require tls` but I'm not sure why this is the case?

Sidenote: Adding `package require tls` causes the script to simply not output any messages, such as `Connection to $url failed` or similar.

**Comment by teeli** [comment]
HTTPS works just fine on my server, so the issue must be somewhere else. Hard to say what it could without more info about the configuration.

**Comment by teeli** [comment]
Is you Eggdrop compiled with TLS support and is SSL proerly configured in Eggdrop config?

**Comment by KeiroD** [comment]
@teeli

Not sure, I'll recompile eggdrop with tls support and check for SSL config in eggdrop config. I'll post back ASAP.

**Comment by KeiroD** [comment]
@teeli Hmm. Odd, I have yet to successfully get it to use SSL for HTTPS...

See config: https://pastebin.com/56ckcDae

**Comment by KeiroD** [comment]
Works for me now... not sure why, but it works. Thanks!
