### ISSUE TITLE
SSL channel error with every URL 

### ISSUE THREAD

**Issue by vzeller** [teeli/urltitle#24]
Some Errors from the Partyline log:

SSL channel "sock55d421723a10": error: tlsv1 alert protocol version
[22:00:12] Connection to https://google.com failed
[22:00:12] Error: connect failed broken pipe
SSL channel "sock55d4217ab1e0": error: wrong version number
[22:00:08] Connection to http://www.wikipedia.com failed
[22:00:08] Error: failed to use socket
SSL channel "sock55d421723a10": error: tlsv1 alert protocol version
[22:00:12] Connection to https://google.de failed
[22:00:12] Error: connect failed broken pipe

Some System Background:
[root@server ~]# uname -a
Linux server 5.17.9-300.fc36.x86_64 #1 SMP PREEMPT Wed May 18 15:08:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Package tdom-0.8.2-32.fc36.x86_64 is already installed.
Package tcltls-1.7.22-5.fc36.x86_64 is already installed.
htmlparse.tcl -> /usr/share/tcl8.6/tcllib-1.20/htmlparse/htmlparse.tcl

**Comment by knofte** [comment]
That's strange, I have tcl-tls:amd64                        1.7.20-1 and do not have problems with old tlsv1 (though google and others respond with /require newer tls)

You're sure the machine doesn't pass through some kind of proxy for https traffic?

**Comment by vzeller** [comment]
It was working before i updated from Fedora 35 to Fedora 36. Did some traceroutes and checked with regular curl wget and the likes. Dont think it is a proxy or transparent proxy. Also rebooted the machine .. disabled selinux. Not sure whats going on, but i suspect that updated package versions like tcltls tdom or htmlparse broke something.

**Comment by vzeller** [comment]
Must have been something with my setup. Resolved.
