### ISSUE TITLE
Some charset problems

### ISSUE THREAD

**Issue by Indjov** [teeli/urltitle#5]
[23:37:23] <03Al> https://www.vbox7.com/play:bb0a7f43b9
[23:37:27] <04ATOM> Title: ÐÐ° ÑÐµÐ·Ð¸ ÑÑÑÐºÐ¸ Ð¼Ð¾Ð¼Ð¸ÑÐµÑÐ° Ð¼Ð¾ÑÐ¶ÑÐ²Ð°Ð½ÐµÑÐ¾ Ð½Ðµ Ðµ Ð¿ÑÐ¾Ð±Ð»ÐµÐ¼ / VBOX7 .
It`s possible to put more charset like cp1251 ?
10x

**Comment by teeli** [comment]
It looks like the URL you posted is using UTF-8 which the script should be able to handle just fine (in fact I just tested with my bot and that link works just fine). Maybe make sure your bot and client both support unicode?

edit. Didn't really answer your question, but the script doesn't really account for any charsets at all. It's all about bot & client configuration.
