### ISSUE TITLE
Errors since latest update

### ISSUE THREAD

**Issue by voidzero** [teeli/urltitle#7]
I'm getting these errors on the partyline:

<pre>
&lt;Bot&gt; [20:08:17] Tcl error [UrlTitle::handler]: error "Unterminated element 'head' (within 'script')" at position 21267
&lt;Bot&gt; "     csm.measure('csm_head_delivery_finished');
&lt;Bot&gt;     }
&lt;Bot&gt;   &lt;/script&gt;
&lt;Bot&gt;         &lt;/head&gt; &lt;--Error--
&lt;Bot&gt;     &lt;body id="styleguide-v2" class="fixed"&gt;
&lt;Bot&gt; &lt;script&gt;
&lt;Bot&gt;     if (typeof uet == 'fu"
&lt;Bot&gt; [20:15:17] Tcl error [UrlTitle::handler]: invalid command name ""
&lt;Bot&gt; [20:28:06] Tcl error [UrlTitle::handler]: error "Unterminated element 'head' (within 'script')" at position 21245
&lt;Bot&gt; "     csm.measure('csm_head_delivery_finished');
&lt;Bot&gt;     }
&lt;Bot&gt;   &lt;/script&gt;
&lt;Bot&gt;         &lt;/head&gt; &lt;--Error--
&lt;Bot&gt;     &lt;body id="styleguide-v2" class="fixed"&gt;
&lt;Bot&gt; &lt;script&gt;
&lt;Bot&gt;     if (typeof uet == 'fu"
&lt;Bot&gt; [20:29:22] Tcl error [UrlTitle::handler]: invalid command name ""
&lt;Bot&gt; [20:39:15] Tcl error [UrlTitle::handler]: error "Unterminated element 'head' (within 'script')" at position 20935
&lt;Bot&gt; "     csm.measure('csm_head_delivery_finished');
&lt;Bot&gt;     }
&lt;Bot&gt;   &lt;/script&gt;
&lt;Bot&gt;         &lt;/head&gt; &lt;--Error--
&lt;Bot&gt;     &lt;body id="styleguide-v2" class="fixed"&gt;
&lt;Bot&gt; &lt;script&gt;
&lt;Bot&gt;     if (typeof uet == 'fu"
&lt;Bot&gt; [20:42:18] Tcl error [UrlTitle::handler]: error "Unterminated element 'head' (within 'script')" at position 20920
&lt;Bot&gt; "     csm.measure('csm_head_delivery_finished');
&lt;Bot&gt;     }
&lt;Bot&gt;   &lt;/script&gt;
&lt;Bot&gt;         &lt;/head&gt; &lt;--Error--
&lt;Bot&gt;     &lt;body id="styleguide-v2" class="fixed"&gt;
&lt;Bot&gt; &lt;script&gt;
&lt;Bot&gt;     if (typeof uet == 'fu"
&lt;Bot&gt; [20:48:33] Tcl error [UrlTitle::handler]: invalid command name ""
</pre>

Any idea what can cause this, and how to fix perhaps?

**Comment by voidzero** [comment]
Derp - forgot to replace &lt; and &gt; with html code entities in the above paste. Fixed this now.

**Comment by voidzero** [comment]
No idea where this comes from. Probably something that causes the script to be terminated preemptively?

**Comment by teeli** [comment]
Probably something to do with the change from regex to xpath. I tried testing it with different test cases that failed with regex earlier and didn't notice any errors. Could you give me an example URL for this?

For a quick fix, you can set tdomSupport to `false` on [line 71](https://github.com/teeli/urltitle/blob/master/urltitle.tcl#L71)

**Comment by voidzero** [comment]
heh well sure, blame my IRC channel for the content of those links :rofl:

The latest URL that failed was this one, and even gave some binary output:

https://pbs.twimg.com/media/C58JTUXXEAIbCUv.jpg

<pre>
[20:28:12] Tcl error [UrlTitle::handler]: error "Missing "&gt;"" at position 73173
"8 £ k¥»ìÓ@ mp.so lÚ¥dn© ×]ºÉ[Þga¼Ù 1çÚ¸l-ä qÝ  ï¢À
 &lt;--Error-- t¢ûåv Èjwo¹ eÕ+0pEÌ´Ãi§ øî Î 'f Ú ®$ kIÛE  ?iö&gt;Å?ã&'5"
</pre>

This URL gave the following output:

https://www.amazon.com/Bro-Custom-Symbol-Tees-Doggy-Yellow/dp/B01EDXDU4M/

<pre>
[20:36:34] Tcl error [UrlTitle::handler]: error "Incorrect &lt!... tag" at position 50987
"/01/gno/sprites/global-sprite_bluebeacon-v1._CB327533540_.png);
  }
--&gt&lt/style&gt
&lt &lt--Error-- ![endif]--&gt
&ltscript type="text/javascript"&gtvar nav_t_after_preload_sprite = + n"
</pre>

And this URL:

http://img.fark.net/images/cache/850/W/Wt/fark_WtjCu6v522v0PIvoDm2QVLDv97U.jpg?t=3GK9fKLvopse5AD0O7kErA&f=1488776400

<pre>
[20:51:42] Tcl error [UrlTitle::handler]: error "Syntax Error" at position 94773
"Ã ?? yÂ pÃ±Â Â Ã =Ã Ã 7/Â Ã ÂºÂ Ã $Â©$Ã Â³Â Â ÂºÂ¶Â Ã¡Â Ã Â±KÀ S`Â ÂžbÂ ?LÂ  &ltb/ &lt--Error-- Â¶sÂ }Ã Â Â Â Ã· &Ãª Ã€?Ã Ã ÂµÂ bzÂ A Ã Ã  Â© Â -H8dÂ Ã¢PÂ£Â hÂ£Â "+Â yÃ RE|RÃ"
</pre>

**Comment by teeli** [comment]
Thanks, that helps. I think I know what's causing this. I'll see if I can fix it over the weekend.

**Comment by voidzero** [comment]
Splendid. Thanks!

**Comment by FevLoad** [comment]
May i add the script does not fetch Twitter‘s urls 
example :
[18:32:08] Connection to https://twitter.com/sport24_tv/status/838757876751613952 failed

**Comment by knofte** [comment]
@Respectme - it works for me
https://twitter.com/illerg/status/838823601226690560
http://cl.motuab.com/0J2u3Q1r453r
Are you sure you run latest version, and have the dependencies installed? (tcl + tls)

**Comment by FevLoad** [comment]
how to make sure that (tcl + tls) is installed ?
Done, everything now is good, and work as it should be 
thank you

**Comment by teeli** [comment]
@voidzero I've updated a new version that at seems to work with those URLs you provided (at least in my test script). If you see any further URLs that cause errors, please report back and I'll see what's up.

**Comment by voidzero** [comment]
Twitter does work for me. But the first url (https://pbs.twimg.com/media/C58JTUXXEAIbCUv.jpg) still yields some problem:

```
[01:53:54] Tcl error [UrlTitle::handler]: error "Missing ">"" at position 73173
"8£k¥»ìÓ@mp.solÚ¥dn©×]ºÉ[Þga¼Ù1çÚ¸l-äqÝï¢À
<--Error-- t¢ûåvÈjwo¹eÕ+0pEÌ´Ãi§øîÎ'fÚ®$     kIÛE?iö>Å?ã&'5"
```

Didn't test the other two yet, will do that tomorrow.

**Comment by teeli** [comment]
That's weird. It shouldn't even try to parse image URLs anymore.

**Comment by voidzero** [comment]
Woops, ok, my bad. I was running eggdrop from a backup location by accident. So it was using the older urltitle.tcl. It does work fine now indeed, thanks again @teeli.

**Comment by teeli** [comment]
Great. Otherwise it would've been pretty mysterious :)

**Comment by voidzero** [comment]
Yeah that's for sure.

I have two more things, might as well put them here. First is trivial, I'd recommend replacing `putserv` with `puthelp` because as I understand it, the puthelp queue is more appropriate for this (something to do with potentially blocking IO iirc, but it's been about 1,5 decade since I learned this convention hehe)

the second is that I just wrote https://www.pastebin.com/ and got back:

```
Tcl error [UrlTitle::handler]: can't read "meta": variable is array
```

**Comment by teeli** [comment]
Apparently the recent changes broke redirection handling, since https://pastebin.com/ redirects to http://pastebin.com/. Should now be fixed.

**Comment by NoAgendaIT** [comment]
Hay!

Found another one.

```Tcl error [UrlTitle::handler]: can't read "meta(Content-Type)": no such element in array```

I wish my TCL-fu was to the degree where I could issue pull requests instead, but it isn't, sorry. Do you have suggestions where I can learn more about TCL?

**Comment by teeli** [comment]
I guess I'll have to check if that key exists in the array. Will check it later.

**Comment by voidzero** [comment]
Woops, NoAgendaIT is me; wrong account.

**Comment by teeli** [comment]
Should be fixed in the latest update.
