### ISSUE TITLE
Problem with some  Punctuation.

### ISSUE THREAD

**Issue by Indjov** [teeli/urltitle#8]
That what i mean is that when you paste some url from youtube like
"Title: Imany - Don't Be So Shy (PanosG Remix) (Unofficial Video) - YouTube" the original title it`s with " ' ". And this tcl can read right this Punctuation.

**Comment by Indjov** [comment]
That what i mean is that when you paste some url from youtube like 
"Title: Imany - Don&#39;t Be So Shy (PanosG Remix) (Unofficial Video) - YouTube" the original title it`s with " ' ". And this tcl can read right this Punctuation.

**Comment by teeli** [comment]
Can you give me the URL to test with?

**Comment by Indjov** [comment]
@teeli , sorry but when i compile my eggdrop again and install tcllib work perfect.
Sorry again for my misunderstood
